=== zongxiaoer/java_changai/intestinal-cancer-sys/service-base-ic/src/main/resources/excel-config/style/styleConfig_1_1.dtd
<!ENTITY % COLOR "(BLACK | SEA_GREEN | AQUA | LIGHT_BLUE | VIOLET | GREY_40_PERCENT | PINK | GOLD | YELLOW | BRIGHT_GREEN | TURQUOISE | DARK_RED | SKY_BLUE | PLUM | 
GREY_25_PERCENT | ROSE | LIGHT_YELLOW | LIGHT_GREEN | BROWN | OLIVE_GREEN | DARK_GREEN | DARK_TEAL |DARK_BLUE | INDIGO | GREY_80_PERCENT | 
ORANGE | DARK_YELLOW | GREEN | TEAL | BLUE | BLUE_GREY | GREY_50_PERCENT | RED | LIGHT_ORANGE | LIME | LIGHT_TURQUOISE | PALE_BLUE | LAVENDER | 
WHITE | CORNFLOWER_BLUE | LEMON_CHIFFON | MAROON | ORCHID | CORAL | ROYAL_BLUE | LIGHT_CORNFLOWER_BLUE 
)">
<!-- border lineType -->
<!ENTITY % LINETYPE "(
BORDER_DASH_DOT | BORDER_DASH_DOT_DOT | BORDER_DASHED | BORDER_DOTTED | BORDER_DOUBLE | BORDER_HAIR | BORDER_MEDIUM | BORDER_MEDIUM_DASH_DOT | 
BORDER_MEDIUM_DASH_DOT_DOT | BORDER_MEDIUM_DASHED | BORDER_SLANTED_DASH_DOT | BORDER_THICK | BORDER_THIN)">
<!ENTITY % UNDERLINE "(
SINGLE_UNDERLINE | SINGLE_UNDERLINE | DOUBLE_UNDERLINE | DOUBLE_UNDERLINE | U_SINGLE_UNDERLINE | U_SINGLE_UNDERLINE | U_DOUBLE_UNDERLINE
)">
<!ENTITY % ALIGN "(CENTER | LEFT | RIGHT | CENTER_SELECTION | FILL | JUSTIFY)">
<!ENTITY % FILLSTYLE "(
SOLID_FOREGROUND | FINE_DOTS | ALT_BARS | SPARSE_DOTS | THICK_HORZ_BANDS | THICK_VERT_BANDS | THICK_BACKWARD_DIAG | THICK_FORWARD_DIAG | 
BIG_SPOTS | BRICKS | THIN_HORZ_BANDS | THIN_VERT_BANDS | THIN_BACKWARD_DIAG | THIN_FORWARD_DIAG | SQUARES | DIAMONDS
)">


<!ELEMENT style-config (font-style,cell-style)>

<!ELEMENT border EMPTY>
<!ATTLIST border type (top|bottom|left|right) #REQUIRED>
<!ATTLIST border lineType %LINETYPE; #IMPLIED>
<!ATTLIST border color %COLOR; #IMPLIED>

<!ELEMENT font EMPTY>
<!ATTLIST font name ID #REQUIRED>
<!ATTLIST font face CDATA #IMPLIED>
<!ATTLIST font size CDATA #IMPLIED>
<!ATTLIST font bold (false|true) #IMPLIED>
<!ATTLIST font italic (false|true) #IMPLIED>
<!ATTLIST font color %COLOR; #IMPLIED>
<!ATTLIST font underLine %UNDERLINE; #IMPLIED>

<!ELEMENT cell (border+)>
<!ATTLIST cell name ID #REQUIRED>
<!ATTLIST cell align %ALIGN; #IMPLIED>
<!ATTLIST cell backgroundColor %COLOR; #IMPLIED>
<!ATTLIST cell fillStyle %FILLSTYLE; #IMPLIED>
<!ATTLIST cell fontStyle CDATA #IMPLIED>
<!ATTLIST cell width CDATA #IMPLIED>
<!ATTLIST cell wrapped (false|true) #IMPLIED>

<!ELEMENT font-style (font+)>
<!ELEMENT cell-style (cell+)>

=== zongxiaoer/java_changai/intestinal-cancer-sys/service-base-ic/src/main/resources/excel-config/style/ExportStyle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE style-config SYSTEM "./styleConfig_1_1.dtd">
<style-config>
	<font-style>
		<font name="test1" face="楷体" size="15" color="GREEN" Bold="true" underLine=""/>
	</font-style>
	<cell-style>
		<cell name="cell1" align="center" backgroundColor="GOLD" fillstyle="SOLID_FOREGROUND" fontStyle="test1" width="5000">
			<border type="top" lineType="BORDER_THIN" color="black" />
			<border type="left" lineType="BORDER_THIN" color="black" />
			<border type="right" lineType="BORDER_THIN" color="black" />
			<border type="bottom" lineType="BORDER_THIN" color="black" />
		</cell>
		<cell name="cell2" align="center" backgroundColor="GOLD" fillstyle="SOLID_FOREGROUND" fontStyle="test1" >
			<border type="top" lineType="BORDER_THIN" color="black" />
			<border type="left" lineType="BORDER_THIN" color="black" />
			<border type="right" lineType="BORDER_THIN" color="black" />
			<border type="bottom" lineType="BORDER_THIN" color="black" />
		</cell>
		<cell name="cell3" align="center" backgroundColor="GOLD" fillstyle="SOLID_FOREGROUND" fontStyle="test1" wrapped="true">
			<border type="top" lineType="BORDER_THIN" color="black" />
			<border type="left" lineType="BORDER_THIN" color="black" />
			<border type="right" lineType="BORDER_THIN" color="black" />
			<border type="bottom" lineType="BORDER_THIN" color="black" />
		</cell>
	</cell-style>
</style-config>
