=== zongxiaoer/java_changai/intestinal-cancer-sys/service-base-ic/src/main/resources/excel-config/exportConfig_1_1.dtd
<!ELEMENT excel (body)>
<!ELEMENT body (table*,iterator*)>
<!ELEMENT table (tr+,iterator*)>
<!ATTLIST table width CDATA #IMPLIED>
<!ELEMENT iterator (table*,tr*,td*)>
<!ATTLIST iterator property CDATA #IMPLIED>
<!ELEMENT tr (td+,iterator*)>
<!ELEMENT td (#PCDATA)>
<!ATTLIST td rowspan CDATA #IMPLIED>
<!ATTLIST td colspan CDATA #IMPLIED>
<!ATTLIST td style CDATA #IMPLIED>

=== zongxiaoer/java_changai/intestinal-cancer-sys/service-base-ic/src/main/resources/excel-config/BloodSampleConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE style-config SYSTEM "./exportConfig_1_1.dtd">
<excel>
	<body>
		<table>
			<tr>
				<td>
					序号
				</td>
				<td>
					SID
				</td>
				<td>
					姓名
				</td>
				<td>
					所属地区
				</td>
				<td>
					所属区
				</td>
				<td>
					所属社区
				</td>
				<td>
					样本ID（前7位）
				</td>
				<td>
					血液采样日期
				</td>
				<td>
					血清冷冻盒编号
				</td>
				<td>
					血清位置
				</td>
				<td>
					血清快递状态
				</td>
				<td>
					血浆冷冻盒编号
				</td>
				<td>
					血浆位置
				</td>
				<td>
					血浆快递状态
				</td>
				<td>
					白细胞冷冻盒编号
				</td>
				<td>
					白细胞位置
				</td>
				<td>
					白细胞快递状态
				</td>
				<td>
					血液样本备注
				</td>
				<td>
					唾液采样日期
				</td>
				<td>
					唾液冷冻盒编号
				</td>
				<td>
					白细胞冷冻盒编号
				</td>
				<td>
					白细胞冷冻盒编号
				</td>
				<td>
					白细胞冷冻盒编号
				</td>
			</tr>
			<tr>
				<td>
					number
				</td>

				<td>
					sid
				</td>
				<td>
					name
				</td>
				<td>
					area_deptId
				</td>

				<td>
					community_dept_id
				</td>
				<td>
					nick_name
				</td>
				<td>
					group
				</td>

				<td>
					release_date
				</td>
				<td>
					fit_code
				</td>
				<td>
					result_date
				</td>

				<td>
					result
				</td>
				<td>
					up_line_value
				</td>
				<td>
					down_line_value
				</td>

				<td>
					in_ten_min
				</td>
				<td>
					no_reson_result
				</td>
			</tr>
			<iterator property="exportResultList">
				<tr>
					<td>
						${number}
					</td>

					<td>
						${sid}
					</td>
					<td>
						${name}
					</td>
					<td>
						${areaDeptId}
					</td>

					<td>
						${communityDeptId}
					</td>
					<td>
						${nickName}
					</td>
					<td>
						${group}
					</td>

					<td>
						${releaseDate}
					</td>
					<td>
						${fitCode}
					</td>
					<td>
						${resultDate}
					</td>

					<td>
						${result}
					</td>
					<td>
						${upLineValue}
					</td>
					<td>
						${downLineValue}
					</td>

					<td>
						${inTenMin}
					</td>
					<td>
						${noResonResult}
					</td>
				</tr>
			</iterator>
		</table>
	</body>
</excel>

=== zongxiaoer/java_changai/intestinal-cancer-sys/service-base-ic/src/main/resources/excel-config/ExportFitConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE style-config SYSTEM "./exportConfig_1_1.dtd">
<excel>
	<body>
		<table>
			<tr>
				<td>
					序号
				</td>
				<td>
					SID
				</td>
				<td>
					姓名
				</td>
				<td>
					所属地区
				</td>
				<td>
					所属区
				</td>
				<td>
					所属社区
				</td>
				<td>
					分组方案（A：A组，B：B组，C：C组，Cd：C组低位，Cg：C组高危）
				</td>
				<td>
					发放日期
				</td>
				<td>
					FIT编码
				</td>
				<td>
					结果录入日期
				</td>
				<td>
					FIT结果（1：阴性 2：阳性 3：无效 4：无结果）
				</td>
				<td>
					上线
				</td>
				<td>
					下线
				</td>
				<td>
					是否10min内读取（ 1：是  0：否）
				</td>
				<td>
					无结果原因
				</td>
			</tr>
			<iterator property="exportResultList">
				<tr>
					<td>
						${number}
					</td>

					<td>
						${sid}
					</td>
					<td>
						${name}
					</td>
					<td>
						${areaName}
					</td>

					<td>
						${depName}
					</td>
					<td>
						${nickName}
					</td>
					<td>
						${group}
					</td>

					<td>
						${releaseDate}
					</td>
					<td>
						${fitCode}
					</td>
					<td>
						${resultDate}
					</td>

					<td>
						${result}
					</td>
					<td>
						${upLineValue}
					</td>
					<td>
						${downLineValue}
					</td>

					<td>
						${inTenMin}
					</td>
					<td>
						${noResonResult}
					</td>
				</tr>
			</iterator>
		</table>
	</body>
</excel>

=== zongxiaoer/java_changai/intestinal-cancer-sys/service-base-ic/src/main/resources/excel-config/ExportConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE style-config SYSTEM "./exportConfig_1_1.dtd">
<excel>
	<body>
		<table>
			<tr>
				<td>
					 姓名
				</td>
				<td>
					年龄
				</td>
			</tr>
			<iterator property="list">
				<tr>
					<td>
						${str}
					</td>

					<td>
						${str1}
					</td>
				</tr>
			</iterator>
		</table>
	</body>
</excel>

=== zongxiaoer/java_changai/intestinal-cancer-sys/service-base-ic/src/main/resources/excel-config/ExportNotificationConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE style-config SYSTEM "./exportConfig_1_1.dtd">
<excel>
    <body>
        <table>
            <tr>
                <td>
                    序号
                </td>
                <td>
                    SID
                </td>
                <td>
                    姓名
                </td>
                <td>
                    所属地区
                </td>
                <td>
                    所属区
                </td>
                <td>
                    所属社区
                </td>
                <td>
                    分组方案
                </td>
                <td>
                    发放方式（1：受试者/家属到社区中心自取，2：社区工作人员入户递送，3：邻居从社区中心捎带取走，4：受试者/家属到医院自取，5：其它，请备注；）
                </td>
                <td>
                    发放日期
                </td>
                <td>
                    发放工作人员
                </td>
                <td>
                    备注
                </td>
            </tr>
<!--            <tr>
                <td>
                    id
                </td>
                <td>
                    sid
                </td>
                <td>
                    name
                </td>
                <td>
                    areaDeptId
                </td>

                <td>
                    communityDeptId
                </td>
                <td>
                    nickName
                </td>
                <td>
                    group
                </td>
                <td>
                    notification_issue_mode
                </td>
                <td>
                    notification_issue_date
                </td>
                <td>
                    notification_issue_worker_code
                </td>
                <td>
                    notification_issue_note
                </td>
            </tr>-->
            <iterator property="exportResultList">
                <tr>
                    <td>
                        ${id}
                    </td>

                    <td>
                        ${sid}
                    </td>
                    <td>
                        ${name}
                    </td>
                    <td>
                        ${areaName}
                    </td>

                    <td>
                        ${depName}
                    </td>
                    <td>
                        ${nickName}
                    </td>
                    <td>
                        ${group}
                    </td>
                    <td>
                        ${notificationIssueMode}
                    </td>
                    <td>
                        ${notificationIssueDate}
                    </td>
                    <td>
                        ${notificationIssueWorkerCode}
                    </td>
                    <td>
                        ${notificationIssueNote}
                    </td>
                </tr>
            </iterator>
        </table>
    </body>
</excel>

=== zongxiaoer/java_changai/intestinal-cancer-sys/service-base-ic/src/main/resources/excel-config/ExportViolationSchemeConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE style-config SYSTEM "./exportConfig_1_1.dtd">
<excel>
	<body>
		<table>
			<!--<tr>-->
				<!--<td>-->
					<!--SID-->
				<!--</td>-->
				<!--<td>-->
					<!--姓名-->
				<!--</td>-->
				<!--<td>-->
					<!--填表日期-->
				<!--</td>-->
				<!--<td>-->
					<!--筛查现场ID-->
				<!--</td>-->
				<!--<td>-->
					<!--工作人员编码-->
				<!--</td>-->
				<!--<td>-->
					<!--检查年份-->
				<!--</td>-->
				<!--<td>-->
					<!--填表人-->
				<!--</td>-->
				<!--<td>-->
					<!--质控者-->
				<!--</td>-->
				<!--<td>-->
					<!--违规种类-筛查对象随机分配无效-->
				<!--</td>-->
				<!--<td>-->
					<!--违规种类-对筛查对象进行了一次以上的随机分配-->
				<!--</td>-->
				<!--<td>-->
					<!--多次随机分配的初始ID-->
				<!--</td>-->
				<!--<td>-->
					<!--违规种类-筛查对象在完成研究前未填写知情同意书-->
				<!--</td>-->
				<!--<td>-->
					<!--违规种类-筛查对象在筛查之前已报告或确诊患有癌症-->
				<!--</td>-->
				<!--<td>-->
					<!--违规种类-随机化分组后的对象接受了其它干预组提供的筛查-->
				<!--</td>-->
				<!--<td>-->
					<!--随机化分组后的对象接受了其它干预组提供的筛查具体说明-->
				<!--</td>-->
				<!--<td>-->
					<!--违规种类-向筛查对象报告了错误的结果-->
				<!--</td>-->
				<!--<td>-->
					<!--违规种类-进行了重复的筛查-->
				<!--</td>-->
				<!--<td>-->
					<!--违规种类-受保护的医疗信息遭泄露-->
				<!--</td>-->
				<!--<td>-->
					<!--违规种类-随机分组分配ID号后，因受试者主观原因在进行到一定程度后决意退出试验-->
				<!--</td>-->
				<!--<td>-->
					<!--受试者退出的主观原因说明-->
				<!--</td>-->
				<!--<td>-->
					<!--受试者退出时预约或完成检查的说明-->
				<!--</td>-->
				<!--<td>-->
					<!--违规种类-其他-->
				<!--</td>-->
				<!--<td>-->
					<!--其他违规种类的说明-->
				<!--</td>-->
				<!--<td>-->
					<!--违规事件发现日期-->
				<!--</td>-->
				<!--<td>-->
					<!--违规事件发生日期-->
				<!--</td>-->
				<!--<td>-->
					<!--随机分配无效原因-年龄小于50或大于74岁-->
				<!--</td>-->
				<!--<td>-->
					<!--随机分配无效原因-曾有医生告诉过患有结直肠癌-->
				<!--</td>-->
				<!--<td>-->
					<!--结直肠癌确诊日期-->
				<!--</td>-->
				<!--<td>-->
					<!--结直肠癌确诊日期为预估日期-->
				<!--</td>-->
				<!--<td>-->
					<!--随机分配无效原因-进行过结直肠癌切除手术-->
				<!--</td>-->
				<!--<td>-->
					<!--随机分配无效原因-正在接受任何癌症相关的治疗（非黑色素皮肤癌除外）-->
				<!--</td>-->
				<!--<td>-->
					<!--随机分配无效原因-在过去5年里，做过结肠镜、乙状结肠镜检查、气钡双重造影、CT仿真结肠镜等结直肠癌筛查；或者CT肠道成像等结直肠癌筛查-->
				<!--</td>-->
				<!--<td>-->
					<!--随机分配无效原因-在过去1年里，接受过粪便潜血检测或者粪便DNA检测-->
				<!--</td>-->
				<!--<td>-->
					<!--随机分配无效原因-有下列下消化道疾病提示需要结肠镜进行确认？1）过去半年中长时间的直肠出血；2）明确诊断的缺铁性贫血；3）过去6个月中有记录的不明原因的体重下降（超过10%基础体重）-->
				<!--</td>-->
				<!--<td>-->
					<!--随机分配无效原因-有其他严重疾病（包括严重的肺部疾病，晚期肾病，晚期肝病、严重的心衰、近期诊断为除黑色素皮肤癌外的其他癌症）-->
				<!--</td>-->
				<!--<td>-->
					<!--随机分配无效原因-未签署知情同意书-->
				<!--</td>-->
				<!--<td>-->
					<!--随机分配无效原因-随机分组后分配ID号后，因受试者主观原因在未接受任何筛查干预前决意退出试验-->
				<!--</td>-->
				<!--<td>-->
					<!--随机分组后分配ID号后，受试者在未接受任何筛查干预前决意退出试验的主观原因说明-->
				<!--</td>-->
				<!--<td>-->
					<!--违反方案内容的具体描述-->
				<!--</td>-->
				<!--<td>-->
					<!--当前年总体状态-->
				<!--</td>-->
			<!--</tr>-->
			<tr>
				<td>
					ssz_id
				</td>
				<td>
					mz
				</td>
				<td>
					tbrq
				</td>
				<td>
					scxc_id
				</td>
				<td>
					i_code
				</td>
				<td>
					c_year
				</td>
				<td>
					tbr
				</td>
				<td>
					zkzr
				</td>
				<td>
					it_1a_1
				</td>
				<td>
					it_1a_2
				</td>
				<td>
					it_1a_2_id
				</td>
				<td>
					it_1a_3
				</td>
				<td>
					it_1a_4
				</td>
				<td>
					it_1a_5
				</td>
				<td>
					it_1a_5_des
				</td>
				<td>
					it_1a_6
				</td>
				<td>
					it_1a_7
				</td>
				<td>
					it_1a_8
				</td>
				<td>
					it_1a_9
				</td>
				<td>
					it_1a_9_cause
				</td>
				<td>
					it_1a_9_des
				</td>
				<td>
					it_1a_10
				</td>
				<td>
					it_1a_10_other
				</td>
				<td>
					it2a1
				</td>
				<td>
					it2b1
				</td>
				<td>
					it_3a_1
				</td>
				<td>
					it_3a_2
				</td>
				<td>
					it_3a_2_time
				</td>
				<td>
					it_3a_2_estimate
				</td>
				<td>
					it_3a_3
				</td>
				<td>
					it_3a_4
				</td>
				<td>
					it_3a_5
				</td>
				<td>
					it_3a_6
				</td>
				<td>
					it_3a_7
				</td>
				<td>
					it_3a_8
				</td>
				<td>
					it_3a_9
				</td>
				<td>
					it_3a_10
				</td>
				<td>
					it_3a_10_cause
				</td>
				<td>
					it_4a_1
				</td>
				<td>
					o_s_c
				</td>
			</tr>
<!--			<tr>
				<td>
					sid
				</td>
				<td>
					name
				</td>
				<td>
					tb_date
				</td>
				<td>
					siteId
				</td>
				<td>
					investigator_code
				</td>
				<td>
					check_year
				</td>
				<td>
					tbr_name
				</td>
				<td>
					zkz_name
				</td>
				<td>
					item_1a_1
				</td>
				<td>
					item_1a_2
				</td>
				<td>
					item_1a_2_id
				</td>
				<td>
					item_1a_3
				</td>
				<td>
					item_1a_4
				</td>
				<td>
					item_1a_5
				</td>
				<td>
					item_1a_5_des
				</td>
				<td>
					item_1a_6
				</td>
				<td>
					item_1a_7
				</td>
				<td>
					item_1a_8
				</td>
				<td>
					item_1a_9
				</td>
				<td>
					item_1a_9_cause
				</td>
				<td>
					item_1a_9_des
				</td>
				<td>
					item_1a_10
				</td>
				<td>
					item_1a_10_other
				</td>
				<td>
					item2a1
				</td>
				<td>
					item2b1
				</td>
				<td>
					item_3a_1
				</td>
				<td>
					item_3a_2
				</td>
				<td>
					item_3a_2_time
				</td>
				<td>
					item_3a_2_estimate
				</td>
				<td>
					item_3a_3
				</td>
				<td>
					item_3a_4
				</td>
				<td>
					item_3a_5
				</td>
				<td>
					item_3a_6
				</td>
				<td>
					item_3a_7
				</td>
				<td>
					item_3a_8
				</td>
				<td>
					item_3a_9
				</td>
				<td>
					item_3a_10
				</td>
				<td>
					item_3a_10_cause
				</td>
				<td>
					item_4a_1
				</td>
				<td>
					overall_status_cy
				</td>
			</tr>-->
			<iterator property="exportResultList">
				<tr>
					<td>
						${sid}
					</td>
					<td>
						${name}
					</td>

					<td>
						${tbDateS}
					</td>
					<td>
						${siteId}
					</td>
					<td>
						${investigatorCode}
					</td>
					<td>
						${checkYear}
					</td>
					<td>
						${tbrName}
					</td>
					<td>
						${zkzName}
					</td>
					<td>
						${item_1a_1}
					</td>
					<td>
						${item_1a_2}
					</td>
					<td>
						${item_1a_2_id}
					</td>
					<td>
						${item_1a_3}
					</td>
					<td>
						${item_1a_4}
					</td>
					<td>
						${item_1a_5}
					</td>
					<td>
						${item_1a_5_des}
					</td>
					<td>
						${item_1a_6}
					</td>
					<td>
						${item_1a_7}
					</td>
					<td>
						${item_1a_8}
					</td>
					<td>
						${item_1a_9}
					</td>
					<td>
						${item_1a_9_cause}
					</td>
					<td>
						${item_1a_9_des}
					</td>
					<td>
						${item_1a_10}
					</td>
					<td>
						${item_1a_10_other}
					</td>
					<td>
						${item2a1}
					</td>
					<td>
						${item2b1}
					</td>
					<td>
						${item_3a_1}
					</td>
					<td>
						${item_3a_2}
					</td>
					<td>
						${item3a2Time}
					</td>
					<td>
						${item_3a_2_estimate}
					</td>
					<td>
						${item_3a_3}
					</td>
					<td>
						${item_3a_4}
					</td>
					<td>
						${item_3a_5}
					</td>
					<td>
						${item_3a_6}
					</td>
					<td>
						${item_3a_7}
					</td>
					<td>
						${item_3a_8}
					</td>
					<td>
						${item_3a_9}
					</td>
					<td>
						${item_3a_10}
					</td>
					<td>
						${item_3a_10_cause}
					</td>
					<td>
						${item_4a_1}
					</td>
					<td>
						${overallStatusCy}
					</td>
				</tr>
			</iterator>
		</table>
	</body>
</excel>

=== zongxiaoer/java_changai/intestinal-cancer-sys/service-base-ic/src/main/resources/excel-config/ExportReviewConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE style-config SYSTEM "./exportConfig_1_1.dtd">
<excel>
	<body>
		<table>
			<!--<tr>-->
<!--&lt;!&ndash;				<td>-->
					<!--序号-->
				<!--</td>&ndash;&gt;-->
				<!--<td>-->
					<!--SID-->
				<!--</td>-->
				<!--<td>-->
					<!--分组-->
				<!--</td>-->
				<!--<td>-->
					<!--姓名-->
				<!--</td>-->
				<!--<td>-->
					<!--身份证号-->
				<!--</td>-->
				<!--<td>-->
					<!--性别-->
				<!--</td>-->
				<!--<td>-->
					<!--出生日期-->
				<!--</td>-->
				<!--<td>-->
					<!--家庭住址-->
				<!--</td>-->
				<!--<td>-->
					<!--联系电话-->
				<!--</td>-->
				<!--<td>-->
					<!--筛查现场ID-->
				<!--</td>-->
				<!--<td>-->
					<!--资格审核日期-->
				<!--</td>-->
				<!--<td>-->
					<!--调查员-->
				<!--</td>-->
				<!--<td>-->
					<!--审核员-->
				<!--</td>-->
				<!--<td>-->
					<!--实足年龄-->
				<!--</td>-->
				<!--<td>-->
					<!--是否曾有医生告诉过您患有结直肠癌-->
				<!--</td>-->
				<!--<td>-->
					<!--是否进行过结肠切除手术-->
				<!--</td>-->
				<!--<td>-->
					<!--是否正在接受任何癌症相关的治疗（非黑色素皮肤癌除外）-->
				<!--</td>-->
				<!--<td>-->
					<!--过去5年中是否有过结肠镜、纤维乙状结肠镜、气钡双对比造影、CT仿真结肠镜检查-->
				<!--</td>-->
				<!--<td>-->
					<!--近1年内是否接受过粪便潜血检测（FOBT）或者粪便DNA检测？-->
				<!--</td>-->
				<!--<td>-->
					<!--是否有下列下消化道疾病或症状提示需要结肠镜进行确诊？1）过去半年中长时间的大便带血；2）明确诊断的缺铁性贫血；3）过去6个月中有记录的不明原因的体重下降（超过10%基础体重）？-->
				<!--</td>-->
				<!--<td>-->
					<!--是否有其他严重疾病（包括严重的肺部疾病，晚期肾病，晚期肝病、严重的心衰、近期诊断为除黑色素皮肤癌外的其他癌症）？-->
				<!--</td>-->
				<!--<td>-->
					<!--非本市户籍常驻人口，且本地居住不足3年？-->
				<!--</td>-->
				<!--<td>-->
					<!--他/她是否不愿意或者不能自己签署知情同意书？-->
				<!--</td>-->
				<!--<td>-->
					<!--当前年总体状态-->
				<!--</td>-->
			<!--</tr>-->
			<tr>
<!--				<td>
					xh
				</td>-->
				<td>
					ssz_id
				</td>
				<td>
					fz
				</td>
				<td>
					xm
				</td>
				<td>
					sfz
				</td>
				<td>
					xb
				</td>
				<td>
					cs_date
				</td>
				<td>
					jtzzp
				</td>
				<td>
					jtzzc
				</td>
				<td>
					jtzza
				</td>
				<td>
					jtzzz
				</td>
				<td>
					jtzzzx
				</td>
				<td>
					jtzz
				</td>
				<td>
					lxdh
				</td>
				<td>
					scxc_id
				</td>
				<td>
					zgsc_date
				</td>
				<td>
					dcy
				</td>
				<td>
					shy
				</td>
				<td>
					it_1
				</td>
				<td>
					it_2
				</td>
				<td>
					it_3
				</td>
				<td>
					it_4
				</td>
				<td>
					it_5
				</td>
				<td>
					it_6
				</td>
				<td>
					it_7
				</td>
				<td>
					it_8
				</td>
				<td>
					it_9
				</td>
				<td>
					it_10
				</td>
				<td>
					o_s_c
				</td>
			</tr>
<!--			<tr>
				<td>
					number
				</td>

				<td>
					sid
				</td>
				<td>
					group
				</td>
				<td>
					name
				</td>
				<td>
					id_card
				</td>
				<td>
					sex
				</td>
				<td>
					birth_date
				</td>

				<td>
					address
				</td>
				<td>
					phone
				</td>
				<td>
					site_id
				</td>

				<td>
					survey_date
				</td>
				<td>
					investigator
				</td>
				<td>
					reviewer
				</td>

				<td>
					item1
				</td>
				<td>
					item2
				</td>
				<td>
					item3
				</td>
				<td>
					item4
				</td>
				<td>
					item5
				</td>
				<td>
					item6
				</td>
				<td>
					item7
				</td>
				<td>
					item8
				</td>
				<td>
					item9
				</td>
				<td>
					item10
				</td>
				<td>
					overall_status_cy
				</td>
			</tr>-->
			<iterator property="exportResultList">
				<tr>
<!--					<td>
						${number}
					</td>-->

					<td>
						${sid}
					</td>
					<td>
						${group}
					</td>
					<td>
						${name}
					</td>
					<td>
						${idCard}
					</td>
					<td>
						${sex}
					</td>
					<td>
						${birthDateToString}
					</td>
					<td>
						${province}
					</td>
					<td>
						${city}
					</td>
					<td>
						${area}
					</td>
					<td>
						${township}
					</td>
					<td>
						${village}
					</td>
					<td>
						${cityOther}
					</td>
					<td>
						${phone}
					</td>
					<td>
						${siteId}
					</td>

					<td>
						${surveyDateToString}
					</td>
					<td>
						${investigator}
					</td>
					<td>
						${reviewer}
					</td>

					<td>
						${item1}
					</td>
					<td>
						${item2}
					</td>
					<td>
						${item3}
					</td>
					<td>
						${item4}
					</td>
					<td>
						${item5}
					</td>
					<td>
						${item6}
					</td>
					<td>
						${item7}
					</td>
					<td>
						${item8}
					</td>
					<td>
						${item9}
					</td>
					<td>
						${item10}
					</td>
					<td>
						${overallStatusCy}
					</td>
				</tr>
			</iterator>
		</table>
	</body>
</excel>

=== zongxiaoer/java_changai/intestinal-cancer-sys/service-base-ic/src/main/resources/excel-config/ExportDnaConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE style-config SYSTEM "./exportConfig_1_1.dtd">
<excel>
    <body>
        <table>
            <tr>
                <td>
                    序号
                </td>
                <td>
                    SID
                </td>
                <td>
                    姓名
                </td>
                <td>
                    所属地区
                </td>
                <td>
                    所属区
                </td>
                <td>
                    所属社区
                </td>
                <td>
                    分组方案（A：A组，B：B组，C：C组，Cd：C组低位，Cg：C组高危）
                </td>
                <td>
                    发放日期
                </td>
                <td>
                    粪便DNA编码
                </td>
                <td>
                    粪便DNA结果（1：阴性 2：阳性 3：无效）
                </td>
                <td>
                    FIT-DNA得分
                </td>
                <td>
                    FIT定量化结果
                </td>
            </tr>
            <iterator property="exportResultList">
                <tr>
                    <td>
                        ${id}
                    </td>

                    <td>
                        ${sid}
                    </td>
                    <td>
                        ${name}
                    </td>
                    <td>
                        ${areaName}
                    </td>
                    <td>
                        ${depName}
                    </td>
                    <td>
                        ${nickName}
                    </td>
                    <td>
                        ${group}
                    </td>
                    <td>
                        ${dna_community_inform_work_time}
                    </td>
                    <td>
                        ${dnaCode}
                    </td>
                    <td>
                        ${dnaCheckResult}
                    </td>
                    <td>
                        ${dnaCheckGoal}
                    </td>
                    <td>
                        ${dnaCheckQuantum}
                    </td>
                </tr>
            </iterator>
        </table>
    </body>
</excel>
